#166840996 Integrate TravisCI with readme badge
andela/ah-nyati-backend pull request #1
Opened 2019-06-25 16:49 UTC by czarjulius

#### What does this PR do?
Setup the travisCI with the readme badge

#### Description of Task to be completed?

- Create the .travis.yml file

- Add the readme badge to readme file

- Integrate the repository to the travisCI.org

#### How should this be manually tested?
N/A

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
<a href="https://www.pivotaltracker.com/story/show/166840996">166840996</a>

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2019-06-25 17:08 UTC, codeBlock-1984 commented
Looks great. However, it seems you forgot to add a new line at the end of your .travis.yml file. Nice job Julius.

2019-06-25 17:13 UTC, codeBlock-1984 reviewed
Looks great. However, it seems you forgot to add a new line at the end of your .travis.yml file. Once you rectify that, I believe you are good to go. Nice job Julius.

2019-06-25 17:41 UTC, Cavdy requested changes
The setup is ok but I noticed you didn't specify the version of node js instead you wrote node... Please correct it... Here is a link to Travis [documentation](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/) on Nodejs

2019-06-25 17:41 UTC, phembarl commented on .travis.yml
> + - 'node'
Add an extra line. Otherwise, LGTM

2019-06-26 10:12 UTC, chokonaira reviewed
good to go

2019-06-26 10:14 UTC, Cavdy reviewed
Looks good to me...

2019-06-26 10:18 UTC, Cavdy approved these changes
Looks good to me...

2019-06-28 08:11 UTC, codeBlock-1984 approved these changes

2019-06-28 11:51 UTC, chokonaira approved these changes

2019-07-01 09:01 UTC, merged