#166841012 Integrate social Login
andela/ah-nyati-backend pull request #17
Opened 2019-07-04 11:24 UTC by Alpha1202

#### What does this PR do?
Integrate Social Login for google, facebook and twitter

#### Description of Task to be completed?
 - install passport
- install passport-facebook
- install passport-google-oauth20
- install passport-twitter
- initialise passport strategies

Have the following endpoints working

`GET /api/auth/google`
`GET /api/auth/facebook`
`GET /api/auth/twitter`

#### How should this be manually tested?
After cloning the repo, cd into the folder and RUN `npm run start:dev`

- on your choice browser, go to any of the routes above

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

- [#166841012](https://www.pivotaltracker.com/story/show/166841012)

#### Screenshots (if appropriate)

- N/A

#### Questions:

- N/A

2019-07-04 22:17 UTC, phembarl approved these changes

2019-07-05 07:02 UTC, codeBlock-1984 approved these changes
Great job @Alpha1202. Looks good to go

2019-07-05 07:36 UTC, czarjulius approved these changes
Looks good to me

2019-07-08 13:57 UTC, fob413 requested changes
Please make these quick changes

2019-07-08 13:57 UTC, fob413 commented on src/config/social_config.js
> +const SerializeSetUp = () => {
please document this function (jsdocs)

2019-07-08 13:57 UTC, fob413 commented on src/controllers/socialController.js
> +      let lName;
Line 27 and 28, can be just a single line

2019-07-08 13:57 UTC, fob413 commented on src/controllers/socialController.js
> +
Please remove all white spaces

2019-07-08 15:04 UTC, closed without merging