#166841003 Integrate coveralls code coverage service
andela/ah-nyati-backend pull request #4
Opened 2019-06-26 14:36 UTC by Alpha1202

#### What does this PR do?

Integrate coveralls code coverage service
Install nyc for code reporting

#### Description of Task to be completed?

integrate ah-nyati-backend on coveralls.io
Install coveralls
install nyc
add coverall badge for test coverage
create .coverall.yml file
write coverall script on package.json
write coveralls-coverage script on package.json

#### How should this be manually tested?

After running the test on your local machine,
Check the coverall badge on the readme.md for the test coverage.

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

#166841003
https://www.pivotaltracker.com/story/show/166841003

#### Screenshots (if appropriate)

N/A

#### Questions:

N/A

2019-06-26 15:24 UTC, Cavdy approved these changes
All good..

2019-06-27 09:41 UTC, phembarl commented on .coveralls.yml
> +repo_token: zdKtmEe7zc0wg8GHKoXRbwfaT5OwLe63F
Please add an extra line here

2019-06-27 10:56 UTC, phembarl commented
LGTM

2019-06-29 17:53 UTC, chokonaira approved these changes
Good

2019-07-01 09:03 UTC, fob413 requested changes
Please make the small changes required and get your teammates to review

2019-07-01 09:03 UTC, fob413 commented on lcov.info
> +TN:
This file should be gitignored

2019-07-01 09:23 UTC, czarjulius approved these changes

2019-07-01 11:52 UTC, fob413 approved these changes

2019-07-01 11:52 UTC, merged