start #166841004 Setup API documentation using swagger
andela/ah-nyati-backend pull request #6
Opened 2019-06-26 19:49 UTC by Alpha1202

#### What does this PR do?

Api documentation using swagger

#### Description of Task to be completed?

install swaggerJSDoc
install swagger-ui-express
configure swagger to look for jsdoc comments in the api folder

#### How should this be manually tested?

After cloning the repo, 
start the server by running `npm run start`
go to `http://localhost:3000/api-docs` to view the documentation

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

#166841004
https://www.pivotaltracker.com/story/show/166841004

#### Screenshots (if appropriate)

#### Questions:
N/A

2019-06-27 09:42 UTC, chokonaira reviewed
looks good

2019-06-27 10:51 UTC, codeBlock-1984 reviewed
Good job @Alpha1202.

2019-07-01 09:09 UTC, fob413 requested changes
Please address the little changes to this PR

2019-07-01 09:09 UTC, fob413 commented on .nyc_output/a3e06063-28ba-443a-902f-72187a7649ed.json
> +{"/Users/nzubechukwunnamani/Desktop/D0/ah-nyati-backend/index.js":{"path":"/Users/nzubechukwunnamani/Desktop/D0/ah-nyati-backend/index.js","statementMap":{"0":{"start":{"line":3,"column":0},"end":{"l
Files like this shouldn't be on GitHub. Please fix this

2019-07-01 12:05 UTC, fob413 approved these changes

2019-07-01 12:05 UTC, czarjulius approved these changes

2019-07-01 12:05 UTC, chokonaira approved these changes

2019-07-01 12:06 UTC, merged

2019-07-01 12:06 UTC, codeBlock-1984 approved these changes