#167809550 reset redirect
andela/ah-nyati-backend pull request #66
Opened 2019-08-09 14:02 UTC by Alpha1202

#### What does this PR do?

- change the reset password redirect url

#### Description of Task to be completed?

- change the reset password redirect url

#### How should this be manually tested?

- N/A

#### Any background context you want to provide?

- User should be able to reset their password

#### What are the relevant pivotal tracker stories?

- [#167809550 ](https://www.pivotaltracker.com/story/show/167809550)

#### Screenshots (if appropriate)
- N/A

#### Questions:
- N/A

2019-08-09 14:45 UTC, chokonaira approved these changes

2019-08-09 14:46 UTC, phembarl approved these changes

2019-08-09 14:47 UTC, czarjulius approved these changes

2019-08-09 15:04 UTC, fob413 requested changes

2019-08-09 15:04 UTC, fob413 commented on src/server.js
> +const server = app.listen(1202, () => {
What is the reason for this change?

2019-08-12 05:45 UTC, Alpha1202 commented on src/server.js
> +const server = app.listen(1202, () => {
Oh, I forgot to revert that.

2019-08-12 20:52 UTC, fob413 approved these changes

2019-08-12 20:53 UTC, merged