#166983634 Fix build script
andela/ah-nyati-backend pull request #9
Opened 2019-06-28 15:45 UTC by phembarl

#### What does this PR do?
- Fixes `build` script

#### Description of Task to be completed?
- Restructures application folder structure
- Rewrite build script using the correct directory

#### How should this be manually tested?
- In the terminal, run the following command: `npm start`
- The server should run successfully

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- #166983634
- https://www.pivotaltracker.com/story/show/166983634

#### Screenshots (if appropriate)
- N/A

#### Questions:
- N/A

2019-06-28 15:56 UTC, chokonaira approved these changes

2019-06-29 15:29 UTC, codeBlock-1984 approved these changes
Good job @phembarl. Looks okay

2019-07-01 09:06 UTC, fob413 requested changes
Please get your other teammates to review.

2019-07-01 11:24 UTC, czarjulius approved these changes

2019-07-01 11:55 UTC, fob413 approved these changes

2019-07-01 11:56 UTC, merged